version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t bank-details-api -f Dockerfile .
     # deploy the image
     - run: |         
         echo "$DOCKERHUB_PASS" | docker login --username yashaswi68 --password-stdin registry.heroku.com
         docker tag aspnetapp registry.heroku.com/bank-details-api/web
         docker push registry.heroku.com/bank-details-api/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a bank-details-api
